### ISSUE TITLE
Easier CLI with Clap?

### ISSUE THREAD

**Issue by seaglade** [BenWiederhake/splaycompress#2]
This is just an idea, but given that you're currently rolling your own interface, have you considered using Clap? It makes parsing arguments pretty simple, and even generates help text from meta comments. Like my other proposal, I can probably make a PR for this at some point if you give me the green light on it.

**Comment by BenWiederhake** [comment]
Absolutely! I even mention it as a TODO somewhere. I just didn't get around to it, because I didn't want to develop it into a real™ tool yet.

Are you on Matrix or Telegram? I'd like to chat with you :)

**Comment by seaglade** [comment]
~~I'm not at the moment sadly, but feel free to email me! If you're on discord, I can email you my tag and we can talk there \^-\^~~

↑ whoops, I lied, I do have telegram. Forgot I had that! I'd rather not post it publicly bc I don't want to get spam, but yeah email me.

**Comment by seaglade** [comment]
Ah, this got closed by #3, whoops. Should have noted that there!
